// Code generated by go-dds-idlgen. DO NOT EDIT.

package sensor

import (
	"github.com/shirou/go-dds-idlgen/cdr"
)

// Ensure cdr import is used.
var _ = cdr.LittleEndian

// SensorData represents the IDL struct SensorData.
type SensorData struct {
	SensorId    int32
	Temperature float64
	Humidity    float32
	Location    string
	Active      bool
}

// CDRExtensibility returns the extensibility kind of SensorData.
func (s *SensorData) CDRExtensibility() cdr.ExtensibilityKind {
	return cdr.FINAL
}

// MarshalCDR serializes SensorData into CDR format with encapsulation header.
func (s *SensorData) MarshalCDR() ([]byte, error) {
	enc := cdr.NewEncoder(cdr.GetEncapsulationKind(s.CDRExtensibility()))
	if err := s.EncodeCDR(enc); err != nil {
		return nil, err
	}
	return enc.Bytes(), nil
}

// UnmarshalCDR deserializes SensorData from CDR format, reading the encapsulation header.
func (s *SensorData) UnmarshalCDR(data []byte) error {
	dec, err := cdr.NewDecoder(data)
	if err != nil {
		return err
	}
	return s.DecodeCDR(dec)
}

// EncodeCDR serializes SensorData using XCDR2 FINAL encoding.
func (s *SensorData) EncodeCDR(enc *cdr.Encoder) error {
	if err := enc.WriteInt32(s.SensorId); err != nil {
		return err
	}
	if err := enc.WriteFloat64(s.Temperature); err != nil {
		return err
	}
	if err := enc.WriteFloat32(s.Humidity); err != nil {
		return err
	}
	if err := enc.WriteString(s.Location); err != nil {
		return err
	}
	if err := enc.WriteBool(s.Active); err != nil {
		return err
	}
	return nil
}

// DecodeCDR deserializes SensorData using XCDR2 FINAL encoding.
func (s *SensorData) DecodeCDR(dec *cdr.Decoder) error {
	{
		v, err := dec.ReadInt32()
		if err != nil {
			return err
		}
		s.SensorId = v
	}
	{
		v, err := dec.ReadFloat64()
		if err != nil {
			return err
		}
		s.Temperature = v
	}
	{
		v, err := dec.ReadFloat32()
		if err != nil {
			return err
		}
		s.Humidity = v
	}
	{
		v, err := dec.ReadString()
		if err != nil {
			return err
		}
		s.Location = v
	}
	{
		v, err := dec.ReadBool()
		if err != nil {
			return err
		}
		s.Active = v
	}
	return nil
}
